import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "RecipeApp.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"bg-contain bg-fixed"} style={{ backgroundImage: `url('https://wallpapercave.com/wp/wp1842836.jpg')` }} >
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
